CREATE TABLE `planner_candidates` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`planner_session_id` text NOT NULL,
	`account_id` text NOT NULL,
	`source_run_id` text NOT NULL,
	`sequence` integer NOT NULL,
	`revision` integer DEFAULT 1 NOT NULL,
	`replaces_candidate_id` text,
	`title` text NOT NULL,
	`content_type` text NOT NULL,
	`content_goal` text NOT NULL,
	`topic` text NOT NULL,
	`angle` text NOT NULL,
	`hook_type` text NOT NULL,
	`hook_idea` text NOT NULL,
	`core_message` text NOT NULL,
	`recommended_reason` text NOT NULL,
	`duplicate_level` text NOT NULL,
	`similar_contents_json` text DEFAULT '[]' NOT NULL,
	`duplicate_reason` text NOT NULL,
	`alternative_angles_json` text DEFAULT '[]' NOT NULL,
	`quality_status` text NOT NULL,
	`quality_issues_json` text DEFAULT '[]' NOT NULL,
	`selectable` integer NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`persisted_content_id` text,
	`is_demo` integer DEFAULT false NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`planner_session_id`) REFERENCES `planner_sessions`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`account_id`) REFERENCES `accounts`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`source_run_id`) REFERENCES `runs`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`replaces_candidate_id`) REFERENCES `planner_candidates`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`persisted_content_id`) REFERENCES `contents`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "planner_candidates_sequence_valid" CHECK("planner_candidates"."sequence" >= 0 AND typeof("planner_candidates"."sequence") = 'integer'),
	CONSTRAINT "planner_candidates_revision_valid" CHECK("planner_candidates"."revision" >= 1 AND typeof("planner_candidates"."revision") = 'integer'),
	CONSTRAINT "planner_candidates_status_valid" CHECK("planner_candidates"."status" IN ('active', 'replaced', 'persisted', 'dismissed')),
	CONSTRAINT "planner_candidates_quality_valid" CHECK("planner_candidates"."quality_status" IN ('passed', 'warning', 'blocked')),
	CONSTRAINT "planner_candidates_duplicate_valid" CHECK("planner_candidates"."duplicate_level" IN ('new', 'mild', 'remixable', 'high'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_planner_candidates_org_id` ON `planner_candidates` (`organization_id`,`id`);--> statement-breakpoint
CREATE UNIQUE INDEX `uq_planner_candidates_active_sequence` ON `planner_candidates` (`organization_id`,`planner_session_id`,`sequence`) WHERE "planner_candidates"."status" = 'active';--> statement-breakpoint
CREATE INDEX `idx_planner_candidates_org_session` ON `planner_candidates` (`organization_id`,`planner_session_id`,`sequence`);--> statement-breakpoint
CREATE TABLE `planner_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`run_id` text NOT NULL,
	`account_id` text NOT NULL,
	`monthly_plan_id` text,
	`context_snapshot_id` text,
	`planned_count` integer NOT NULL,
	`shoot_date` text,
	`primary_goal` text NOT NULL,
	`special_requirements` text,
	`planning_summary` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'generating' NOT NULL,
	`planner_skill_version` integer NOT NULL,
	`planner_point_cost` integer NOT NULL,
	`selected_count` integer DEFAULT 0 NOT NULL,
	`created_by` text NOT NULL,
	`is_demo` integer DEFAULT false NOT NULL,
	`completed_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`run_id`) REFERENCES `runs`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`account_id`) REFERENCES `accounts`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`account_id`,`monthly_plan_id`) REFERENCES `monthly_plans`(`organization_id`,`account_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`context_snapshot_id`) REFERENCES `context_snapshots`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`organization_id`,`created_by`) REFERENCES `users`(`organization_id`,`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "planner_sessions_count_valid" CHECK("planner_sessions"."planned_count" BETWEEN 1 AND 20 AND typeof("planner_sessions"."planned_count") = 'integer'),
	CONSTRAINT "planner_sessions_point_cost_valid" CHECK("planner_sessions"."planner_point_cost" >= 0 AND typeof("planner_sessions"."planner_point_cost") = 'integer'),
	CONSTRAINT "planner_sessions_selected_count_valid" CHECK("planner_sessions"."selected_count" BETWEEN 0 AND "planner_sessions"."planned_count"),
	CONSTRAINT "planner_sessions_status_valid" CHECK("planner_sessions"."status" IN ('generating', 'awaiting_selection', 'completed', 'failed')),
	CONSTRAINT "planner_sessions_goal_valid" CHECK("planner_sessions"."primary_goal" IN ('exposure', 'followers', 'trust', 'click', 'conversion', 'gmv'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_planner_sessions_org_id` ON `planner_sessions` (`organization_id`,`id`);--> statement-breakpoint
CREATE UNIQUE INDEX `uq_planner_sessions_org_run` ON `planner_sessions` (`organization_id`,`run_id`);--> statement-breakpoint
CREATE INDEX `idx_planner_sessions_org_account_created` ON `planner_sessions` (`organization_id`,`account_id`,`created_at`);